### PR TITLE
Create TravelAgency_Screen

### PR DESCRIPTION
**Pull request by soumyajindal0707**

### CODE REVIEW

**Comment by SimPandit** [comment]
Hi @soumyajindal0707 . Great work with the Travel agency Home page. Just 1 suggestion, it is always recommended to use no more than 2 fonts in your designs. So, you make choose 2 fonts that suit best your design and use them. Not more than 2.

**Comment by soumyajindal0707** [comment]
hey I have updated my design pls check it out @SimPandit

**Comment by soumyajindal0707** [comment]
Hey I have made the changes. Pls check.

**Comment by soumyajindal0707** [comment]
Hi @SimPandit. I have added one more UX-UI project on the TravelAgency
Issue. Please check.

You can find it under my previous PR for PetAdoption UX-UI project.

**Comment by soumyajindal0707** [comment]
Hi,

I have added more UX-UI designs for favorite superheroes tinder profiles.
Please merge them too if possible.

Thank you

**Pull request merged**
