### PR TITLE
Design an health tracking features for your smart watch. Fix issue #10

### PR DESCRIPTION
**Pull request by kashisha3**
created a design on figma and attached its link.

### CODE REVIEW

**Comment by SimPandit** [comment]
Hi @kashisha3, you needed to design a smartwatch interface, not a webpage.

**Comment by kashisha3** [comment]
@SimPandit I have made the changes in the design.

**Comment by SimPandit** [comment]
@kashisha3 what tool have you used for designing? Seems like you have added images of various icons. Try to add vector icons of the same family and then the design would look awesome.

**Comment by kashisha3** [comment]
@SimPandit Done the changes. Please look at it once and tell if more changes are required. Thanks

**Pull request merged**
