### PR TITLE
Design added

### PR DESCRIPTION
**Pull request by Nitya-Pasrija**
With ref to #84 
@SimPandit

### CODE REVIEW

**Comment by SimPandit** [comment]
@Nitya-Pasrija how will the user get in touch? there are no contact details. I believe more content can be added, since its the landing page.

**Comment by Nitya-Pasrija** [comment]
I'll add the footer note then

**Comment by Nitya-Pasrija** [comment]
@SimPandit

**Comment by SimPandit** [comment]
great!

**Pull request merged**
