### PR TITLE
Landing Page for Food Ordering App

### PR DESCRIPTION
**Pull request by ASHWINISHARMABTCSAI118**

### CODE REVIEW

**Comment by SimPandit** [comment]
@ASHWINISHARMABTCSAI118 Good one. Just one thing that there is an alignment issue. You will see that "Order Again" and "Fastest Near you" are not on the same vertical line. Also, the top carousel image is not aligned with the below images.

**Comment by ASHWINISHARMABTCSAI118** [comment]
Should I make changes and re-upload again?

**Comment by ASHWINISHARMABTCSAI118** [comment]
I have commited changes please review it.

**Comment by ASHWINISHARMABTCSAI118** [comment]
@SimPandit I have raised a pr for the same with suggested changes, So declining this pr. link for the new pr is : https://github.com/GDSC-IGDTUW-Autumn-of-Code-2022/UX-UI-Case-Studies-and-Projects/pull/36

**Pull request closed without merging**
